# Generated by Django 4.2.7 on 2023-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='durations',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
