# Generated by Django 4.2.7 on 2023-11-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffprofile_staff_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.IntegerField(null=True),
        ),
    ]
